In [27]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

In [28]:
df = pd.read_csv("../data_set/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,52,1,1,118,186,0,2,190,0,0.0,2,0,fixed,0
299,43,0,4,132,341,1,2,136,1,3.0,2,0,reversible,1
300,65,1,4,135,254,0,2,127,0,2.8,2,1,reversible,1
301,48,1,4,130,256,1,2,150,1,0.0,1,2,reversible,1
302,63,0,4,150,407,0,2,154,0,4.0,2,3,reversible,1

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    str
 13  target    303 non-null    int64
dtypes: float64(1), int64(12), str(1)
memory usage: 33.3 KB

In [30]:
df["thal"].unique()

<StringArray>
['fixed', 'normal', 'reversible', '1', '2']
Length: 5, dtype: str

In [31]:
X = df.drop(columns=["target"])
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,52,1,1,118,186,0,2,190,0,0.0,2,0,fixed
299,43,0,4,132,341,1,2,136,1,3.0,2,0,reversible
300,65,1,4,135,254,0,2,127,0,2.8,2,1,reversible
301,48,1,4,130,256,1,2,150,1,0.0,1,2,reversible
302,63,0,4,150,407,0,2,154,0,4.0,2,3,reversible

In [32]:
y = df["target"]
y

0      0
1      1
2      0
3      0
4      0
      ..
298    0
299    1
300    1
301    1
302    1
Name: target, Length: 303, dtype: int64

In [33]:
X = pd.get_dummies(
    X,
    columns=["thal"],
)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal_1,thal_2,thal_fixed,thal_normal,thal_reversible
0,63,1,1,145,233,1,2,150,0,2.3,3,0,False,False,True,False,False
1,67,1,4,160,286,0,2,108,1,1.5,2,3,False,False,False,True,False
2,67,1,4,120,229,0,2,129,1,2.6,2,2,False,False,False,False,True
3,37,1,3,130,250,0,0,187,0,3.5,3,0,False,False,False,True,False
4,41,0,2,130,204,0,2,172,0,1.4,1,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,52,1,1,118,186,0,2,190,0,0.0,2,0,False,False,True,False,False
299,43,0,4,132,341,1,2,136,1,3.0,2,0,False,False,False,False,True
300,65,1,4,135,254,0,2,127,0,2.8,2,1,False,False,False,False,True
301,48,1,4,130,256,1,2,150,1,0.0,1,2,False,False,False,False,True
302,63,0,4,150,407,0,2,154,0,4.0,2,3,False,False,False,False,True

# Perform PCA

In [34]:
pca_full = PCA()
pca_full.fit(X)
pca_full.explained_variance_ratio_

array([7.45786435e-01, 1.51912846e-01, 8.50131739e-02, 1.58839483e-02,
       4.08549255e-04, 2.53939093e-04, 2.47975391e-04, 1.85384237e-04,
       1.08338039e-04, 6.03689933e-05, 4.34215513e-05, 4.17992904e-05,
       3.12009516e-05, 2.04284196e-05, 1.34833575e-06, 8.43122549e-07,
       0.00000000e+00])

In [35]:
np.cumsum(pca_full.explained_variance_ratio_ * 100)

array([ 74.57864349,  89.76992811,  98.2712455 ,  99.85964033,
        99.90049526,  99.92588917,  99.95068671,  99.96922513,
        99.98005893,  99.98609583,  99.99043799,  99.99461792,
        99.99773801,  99.99978085,  99.99991569, 100.        ,
       100.        ])

In [36]:
pca_99 = PCA(n_components=4)
X_pca = pca_99.fit_transform(X)
X_pca

array([[-12.63468219,  -2.60545109,  14.81816011,   6.67127905],
       [ 40.66152405, -46.21681683,  20.43617991,   0.19630235],
       [-17.83960046, -20.36748443, -12.34921485,  11.19813037],
       ...,
       [  7.70952661, -23.96508241,   0.47123956,   5.92061878],
       [  9.1476144 ,   2.22470068,  -2.91695677,  -6.24831049],
       [161.35981523,   0.88447062,  11.56906489,   1.78024855]],
      shape=(303, 4))

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.3, random_state=42
)
print("X_train")
print(X_train.shape)
print("X_test")
print(X_test.shape)
print("y_train")
print(y_train.shape)
print("y_test")
print(y_test.shape)

X_train
(212, 4)
X_test
(91, 4)
y_train
(212,)
y_test
(91,)

In [38]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 0.27892867309408037
Coefficients: [ 0.00080628 -0.00794492  0.00162875 -0.00291936]

In [39]:
predictions = model.predict(X_test)

print(predictions)

[ 0.34868906  0.38620448  0.11504383  0.06528095  0.25727986  0.22731936
  0.5997354   0.27373618  0.19038813  0.18056358  0.00299594  0.37515017
 -0.0372388   0.5049257   0.66316643  0.43103265  0.5793347   0.83892054
 -0.05550206  0.20089649  0.38934849  0.09727919  0.38069214  0.15547441
  0.57542002  0.27799399  0.29099818  0.11757803  0.34822964  0.09806634
  0.56596671  0.18316176  0.64808601  0.13920569  0.21413318  0.0787619
  0.38875701  0.34980762  0.37170765  0.26166233  0.43977635  0.06785203
  0.31945048  0.25764683  0.21368883  0.45018719  0.35244976  0.10627112
  0.14361846  0.40519084  0.31176093  0.24250702 -0.07177248  0.02889629
  0.22080388  0.50373283  0.37090558  0.63320866  0.45902853  0.11002269
  0.29476403  0.30805443  0.0379533   0.30031826  0.65573451  0.31158045
  0.28625802  0.14665836  0.228099    0.09850117  0.26755634  0.18130067
  0.36501363  0.06408968  0.50542963  0.0966033   0.01168028  0.25585998
  0.35507829 -0.01071328  0.28376662  0.32523898  0.19775575  0.69107188
  0.0638659   0.06807631  0.32470628  0.12206808  0.48550993  0.26855548
  0.27947397]